### PR TITLE
<LOL>Goodbye, Mat Selling

### PR DESCRIPTION
**Pull request by Yawet330**
## About The Pull Request
Removes the ability to directly convert materials into caps via the shop or other means. (tram)

## Why It's Good For The Game
You brought this on yourselves. Six rounds of forced Gapple abuse to produce infinite gold to buy infinite PA is what got this removed.

This fixes an infinite wealth glitch involving materials.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
del: Selling mats for caps
/:cl:

### CODE REVIEW

**Comment by iMoeMoe** [comment]
Wait so this means you're just gonna remove the Trade Points vendor completely?

**Comment by Pokebutt** [comment]
> So you also removed things that can't be duped like diamonds that people could just mine up?

yes the did I looked over the code

**Comment by AllCorruptingWyrm** [comment]
By getting rid of cap farms you are just going to make BoS go out more.
I hope you know what that means.

+1 regardless, just hope you know what you're doing.

**Comment by iMoeMoe** [comment]
> > Reference in ne
> 
> Diamonds can be duped, I'm just not stating how.

Destructive Analyser dupe doesn't exist here if you didn't know

**Comment by ApplePlastic** [comment]
> By getting rid of cap farms you are just going to make BoS go out more. I hope you know what that means.
> The point. People want them to go to bunkers for loot like everyone else. 

Seeing this closed was incredibly disappointing. It is what it is.

**Pull request closed without merging**
