### PR TITLE
Synths & Stimpaks

### PR DESCRIPTION
**Pull request by panzerr1944**
## About The Pull Request
This PR does nothing but make it so Stimpaks, Imitation Stimpaks and Super Stimpaks heal the same to Synths as they do to Organics by doubling the initial values to closer match said standard values

## Why It's Good For The Game
Synths, as they stand, aren't all that good. Stimpaks as they stand especially do little to nothing for a Synth and it takes many just to get to full HP without using a welder or cables. Stimpaks are the ONLY med-chem synths can use, too. So rather then have them hard-nerfed simply because they're a 'gimmick species', let's make them more worth using on a mechanical level rather than gimping people who want to play them. Even ghouls are better right now, and they're in a pretty bad state as it stands.

I'm aware in an ahelp Jasrick, you said and I quote 'Yep, which we're not doing' on my question on how to rectify the issue of Synths hardly getting any healing from Stimpaks. I fully expect you might just straight up close this without a second thought, although I'll politely request you don't, and rather merge it. Make Synths worth playing on a non-fluff level. Please.

## Changelog
tweak: Stim-healing for Synthetics (doubled existing values, as they were half normal)

### CODE REVIEW

**Comment by JasmineRickards** [comment]
Too many straight upgrades, tries to make synths better than humans.

**Comment by panzerr1944** [comment]
> Too many straight upgrades, tries to make synths better than humans.

This isn't true at all though.
Synthetics, while they don't need to eat, sleep or drink, **cannot use any chem that isn't Stimpaks at the moment. They just don't work properly, or in most cases at all.** This gives any and all other races a MASSIVE advantage. No synthflesh, no bruise packs, none of it. Just stimfluid, cables and welders.
Synthetics are hyper-vulnerable to EMPs, being blinded and heavily damaged by them, and ontop of that can be easily de-limbed. Yes, they can re-attach them easily, but the fact they can be delimbed so quickly makes their combat capabilities as weak as a ghouls... except without the ghouls **inability to go into crit, which is comically strong in comparison to the slight fix here**
Synths can also still get wounds. Big wounds, which ties into the prior mentioned easy-delimb and makes them even weaker in comparison to ghouls and humans. Ghouls can also be easy-delimbed, but they are granted passive radiation healing.
Synthetics as it stands are arguably the worst race of them all. This is hardly a straight upgrade that'll make them better than humans, as that'll never happen so long as they can be 3shot by a good EMP like they can currently, or otherwise completely put out of the fight nigh instantly by arm-targeting. 

All this PR does is make stims work like normal on synths, evening the playing field that's currently not at all tilted in a Synthetic players favour. This does not make them 'better than humans' at all.

**Comment by JasmineRickards** [comment]
The current values you provided makes it MORE effective on synths than people. I get the part about EMP vulnerabilities, but that's intentional. Synth players are meant to be pre-war machines. They aren't particularly good but get utility values.

**Comment by panzerr1944** [comment]
> The current values you provided makes it MORE effective on synths than people. I get the part about EMP vulnerabilities, but that's intentional. Synth players are meant to be pre-war machines. They aren't particularly good but get utility values.

Then what values would you suggest? The current values make stimpaks simply not worth using at all, as you need to chug them like koolaid to get to full hp, or use super-stims exclusively and hope you dont OD. As it stands I just doubled the numbers, although I'm happy to edit such if you'd re-open the PR.

**Comment by JasmineRickards** [comment]
Current values make it so welders and cables are an alternative rather than a necessity.

**Pull request closed without merging**
